filebeat.autodiscover:
    providers:
      - type: docker
        templates:
          - condition:
              and:
                - has_fields: ['docker.container.labels.elastic_index', 'docker.container.labels.send.logs']
                - equals:
                    docker.container.labels.send.logs: "true"
            config:
              - type: docker
                json.keys_under_root: true
                json.add_error_key: true
                json.message_key: log
                containers:
                  ids:
                    - "${data.docker.container.id}"
  processors:
    - add_docker_metadata: ~
  
  setup.template.enabled: true
  setup.template.name: "m4u-template"
  setup.template.pattern: "m4u-logs"
  
  setup.ilm.enabled: false
  setup-ilm-policy_name: "m4u-policy"
  
  output.elasticsearch:
    protocol: http
    hosts: ["http://192.168.0.106:9200"]
    index: "alias-write-m4u-logs"  